#!/bin/bash


#cp ../../Rabbits/platforms/bunny/mem_init .
cp ../../Rabbits/platforms/bunny/mem_shared .

./sherlock --pg watson ../../Rabbits/platforms/bunny/WS.hwe --elf /work/cunha/devel/Rabbits/platforms/bunny/soft/splash-2/codes/apps/water-spatial/waterspatial
