# Automatically generated by configure - do not modify
SRC_PATH=/home/cunha/devel/TIMA/reverse/reverse/platform/hardware/rabbits/rabbits/qemu/sc_qemu/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
LD=ld
