#CC := gcc
CC     := /opt/toolchains/dnaos/arm/bin/$(APES_COMPILER)
CFLAGS := -O3 -D_POSIX_C_SOURCE=200112 -DSOCLIB
#CFLAGS := -g3 -pthread -D_POSIX_C_SOURCE=200112
CFLAGS := $(CFLAGS) -Wall -W -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wdisabled-optimization
CFLAGS := $(CFLAGS) -Wpadded -Winline -Wpointer-arith -Wsign-compare -Wendif-labels
LDFLAGS := -lm

BASEDIR := $(SPLASH_DIR)/codes
#MACROS := $(BASEDIR)/null_macros/c.m4.null.POSIX
MACROS := $(BASEDIR)/null_macros/c.m4.null.POSIX_DNA_OS
M4 := m4 -s -Ulen -Uindex

x = *

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(CFLAGS) -o $(TARGET) $(LDFLAGS)

clean_old:
	rm -rf *.c *.h *.o $(TARGET)
	rm bin/*

.SUFFIXES:
.SUFFIXES:	.o .c .C .h .H

.H.h:
	$(M4) $(MACROS) $*.H > $*.h

.C.c:
	$(M4) $(MACROS) $*.C > $*.c

.c.o:
	$(CC) -c $(CFLAGS) $*.c

.C.o:
	$(M4) $(MACROS) $*.C > $*.c
	$(CC) -c $(CFLAGS) $*.c
