SUBDIRS = sources
BUILDDIR := $(BUILDDIR)/SYSTEM_SSP_CAL_XILINX_MICROBLAZE_81I_NEW

default: apes_submake

clean : apes_clean

ifdef MAKEFILE_RULES
include $(MAKEFILE_RULES)
else
include $(APES_HOME)/support/Makefile.rules
endif

